### ISSUE TITLE
You'll never beat amogos :)

### ISSUE THREAD

**Issue by NoozAbooz** [Villagerjj/sus-os#1]
:           )

*activate sabotage*

**Comment by Villagerjj** [comment]
I know, But I sure can try.
 : )

**Comment by leha-code** [comment]
Don't worry he's always that toxic to other people's projects hee doesn't like

**Comment by NoozAbooz** [comment]
> Don't worry he's always that toxic to other people's projects hee doesn't like

The heck is this leha? This is all in good trolling, I value all projects and the work put into them except those made by bullies like you.
